site_name: AquaCrop-OSPy
theme:
  name: material

repo_url: https://github.com/aquacropos/aquacrop

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [.]
                options:
                    show_root_heading: true
                    heading_level: 2

    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True


nav:
  - Home: index.md

  - Notebooks:
    - Getting Started: notebooks/AquaCrop_OSPy_Notebook_1.ipynb
    - Estimating Irrigation Demand: notebooks/AquaCrop_OSPy_Notebook_2.ipynb
    - Optimizing Irrigation: notebooks/AquaCrop_OSPy_Notebook_3.ipynb
    - Climate Change Impacts: notebooks/AquaCrop_OSPy_Notebook_4.ipynb
    - Comparison with AquaCrop Windows: notebooks/05_comparison.ipynb

  - API:
    - Core: core.md
    - Entities: entities.md
    - Initialize: initialize.md
    - Solution: solution.md
    - Timestep: timestep.md
    - Utils: utils.md
    # - Lars: lars.md